### ISSUE TITLE
[Bug] When it rains, a strange display effect appears on the edge of the sea.

### ISSUE THREAD

**Issue by OcrSu** [sixthsurge/photon#10]
Disappears after turning off the rain effect, hope to fix or improve.
https://user-images.githubusercontent.com/75876201/236375549-5061b9fc-3b0d-48f3-b011-1656b38d7e64.mp4

1.18.2 Forge OptiFine_1.18.2_HD_U_H9_pre3
GPU:RX6800 Driver Version:23.4.2

**Comment by sixthsurge** [comment]
already fixed in the nest version :) as well as many other issues with translucent blending

**Comment by OcrSu** [comment]
I downloaded and used the db91ccc version, which is Clone down in Github to use.
To be honest I'm not sure on which platform you have released this Photon Shader.
Looking forward to your next update.

> already fixed in the next version :) as well as many other issues with translucent blending

**Comment by sixthsurge** [comment]
you're in the right place, it will be released here on GitHub
