### ISSUE TITLE
Distant Horizon compatibility

### ISSUE THREAD

**Issue by XDarkDreamsX** [sixthsurge/photon#101]
### Description

i would like to have a distant horizons compatibility patch

**Comment by 0hStormy** [comment]
Would look so cool.

**Comment by owosoup** [comment]
I'll second this, too. I guess it'll take some work but it would definitely up this shader's level by a notch.

**Comment by owosoup** [comment]
Thanks so much ! Your shader's amazing.

**Comment by sixthsurge** [comment]
added
