### ISSUE TITLE
1.16.5?

### ISSUE THREAD

**Issue by ISE9218** [sixthsurge/photon#109]
### Question

Does this shader work on 1.16.5?

**Comment by Candymanmax** [comment]
try it and find out

**Comment by ISE9218** [comment]
> try it and find out, it should work

Ok

**Comment by Patomosm** [comment]
Yes, it works with 1.6.17 too.

**Comment by 0hStormy** [comment]
Honestly shaders work most of the time on almost any version, with some caveats.

**Comment by Patomosm** [comment]
Remember that "colored lighting" is a fabric/Iris feature, not forge/optifine's.
So... photon do work with 1.6.15 and above. 100% with Iris, less with optifine.

Use this mods with Iris and Minecraft 1.20.4 for the best results:
![image](https://github.com/sixthsurge/photon/assets/133518090/870c6139-2ca0-4ffe-a317-461e3334562e)

**Comment by ISE9218** [comment]
> Remember that "colored lighting" is a fabric/Iris feature, not forge/optifine's. So... photon do work with 1.6.15 and above. 100% with Iris, less with optifine.
> 
> Use this mods with Iris and Minecraft 1.20.4 for the best results: ![image](https://private-user-images.githubusercontent.com/133518090/310554190-870c6139-2ca0-4ffe-a317-461e3334562e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Mzg5NjEsIm5iZiI6MTcwOTczODY2MSwicGF0aCI6Ii8xMzM1MTgwOTAvMzEwNTU0MTkwLTg3MGM2MTM5LTJjYTAtNGZmZS1hMzE3LTQ2MWUzMzM0NTYyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxNTI0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTFkZjVlMDllYzRlOGRiOWU3ZDhlYjhkZWZiM2ZjMzM1MjA0ZmM0Yjk2Y2JhMTMyYjU4MDM0MzY5ZGQzNDM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5AHUvLJY3vRpgyUPmLHSigoRE0nYE6TiHcamFKkt7mI)

I see but im currently playing a modpack that uses optifine so I'm fine with not having colored lighting. Thanks for the recommendations.
