### ISSUE TITLE
Strange water render bug

### ISSUE THREAD

**Issue by FracturedCrow** [sixthsurge/photon#11]
at the edge between water and ice, the water wave will covered with a reflection of it. It waves and looks strange. 
![Screenshot 2023-05-11 05-26-15](https://github.com/sixthsurge/photon/assets/133167563/e5bd538a-a7d6-4c44-bb8c-795b1bae5bcc)

**Comment by Patomosm** [comment]
It happens to me too. With custom texture pack it feels more realistic. I think the presence of ice's reflaction is perfectly normal, perhaps the intensity is too much equal to the block of ice.

![immagine](https://github.com/sixthsurge/photon/assets/133518090/5d9bd85b-d595-4098-9665-588caf787db7)

**Comment by roboboredom** [comment]
> It happens to me too. With custom texture pack it feels more realistic. I think the presence of ice's reflaction is normal, perhaps the intensity should not be a perfect mirror.
> 
> ![immagine](https://user-images.githubusercontent.com/133518090/239027536-5d9bd85b-d595-4098-9665-588caf787db7.png)

P.S. for the developer: this user is using Patrix resource pack.

**Comment by sixthsurge** [comment]
fixed
