### ISSUE TITLE
Blocky Clouds error

### ISSUE THREAD

**Issue by TedAlter** [sixthsurge/photon#128]
### What happened?

Actualy I`m plaing on 1.20.4 but these shaders worked well with blocky clouds before I replaced it with latest version.I just wanted to play with blocky clouds.

### Minecraft Version

1.20.2

### Which shader mod are you using?

Iris

### Shader mod version

1.7.0 snapshot +mc1.20.4fcec4d

### Shader settings

```conf
#Sat Apr 06 20:35:25 EEST 2024
POM_SHADOW=true
COLORED_LIGHTS=true
shadowMapResolution=4096
SPECULAR_MAPPING=true
BLOCK_ENTITY_SHADOWS=true
NORMAL_MAPPING=true
INFO=3
POM=true
BLOCKY_CLOUDS=true
WATER_CAUSTICS=true
AIR_FOG_COLORED_LIGHT_SHAFTS=true
```

### Relevant log output

```text
deferred4.fsh: deferred4.fsh: 0(1778) : error C1503: undefined variable "blocky_clouds"
0(1778) : error C1503: undefined variable "blocky_clouds"
```

**Comment by sixthsurge** [comment]
fixed in dev branch
