### ISSUE TITLE
Not enough emitted color light from torches.

### ISSUE THREAD

**Issue by Patomosm** [sixthsurge/photon#14]
Screenshots are taken in a deep cave, in deepslate blocks wall.
The torches are placed inside two blocks of depth to test the intensity of the light emitted.
**As you can see, no color can be distinguished and you do not see the light coming out of the holes.**

![immagine](https://github.com/sixthsurge/photon/assets/133518090/a453b979-2fb9-45a3-b578-6b8a9a03a718)

![immagine](https://github.com/sixthsurge/photon/assets/133518090/06c4cafc-4b80-47de-b580-33a50d570ec7)

![immagine](https://github.com/sixthsurge/photon/assets/133518090/3dffb5a2-94d2-4b28-80c2-26b3978bf7e7)

**I add that I would like to see the colors even holding the torches in my hand. Not too intense but recognizable.**

**Comment by Xposeded** [comment]
I think it's fine. The intensity of light is based on Minecraft's internal lightmap algorithm, which can't be as realistic as other "Path Tracing" Shaders could provide.

**Comment by Patomosm** [comment]
Thanks Xposeded, I understand.
At least I would like to see the colors in a next wall when holding the torches in my hand. Not too intense but recognizable.
Another question:
Is it possible to add glgs path tracing to some lights, like torches (3 colors), fires and campfires (2 colors) and end-rod?
Sorry for my ignorance.

**Comment by Xposeded** [comment]
> Thanks Xposeded, I understand. At least I would like to see the colors in a next wall when holding the torches in my hand. Not too intense but recognizable. Another question: Is it possible to add glgs path tracing to some lights, like torches (3 colors), fires and campfires (2 colors) and end-rod? Sorry for my ignorance.

I've implemented a simple colored held lighting method (without path tracing): https://github.com/Xposeded/photon_modified
I hardcoded 5 types of colors, you can add more colors by modifying the source code, if you like.

![image](https://github.com/sixthsurge/photon/assets/26787211/c990df82-ca21-41eb-ae37-95b90a93e42c)

**Comment by Patomosm** [comment]
I use Optifine and I did't see improvement. I'm sorry.
If you can make it work with Optifine as well, I'll definitely add more colors to the source code.

**Comment by Xposeded** [comment]
> I use Optifine and I did't see improvement. I'm sorry. If you can make it work with Optifine as well, I'll definitely add more colors to the source code.

I tested it on Minecraft 1.19.4, with fabric, "optifabric-1.13.24" and "OptiFine_1.19.4_HD_U_I4", nothing went wrong. I have no idea why it didn't work for you. by the way, are you sure the shade pack you're using is the right one that was modified by me?
![image](https://github.com/sixthsurge/photon/assets/26787211/963ada56-1a14-4779-9ba5-9fbd48b5cc08)
![image](https://github.com/sixthsurge/photon/assets/26787211/f82c3e5e-8e73-46aa-8430-9b284fdfd001)
![image](https://github.com/sixthsurge/photon/assets/26787211/a728037c-1789-48e7-bc68-f2ebda38630a)
![image](https://github.com/sixthsurge/photon/assets/26787211/7e4cc279-4f95-460f-9012-d304d01ab96a)

**Comment by Patomosm** [comment]
I do use Minecraft 1.19.4 with OptiFine_1.19.4_HD_U_I4 too, but with Forge (45.0.66), not with Fabric.
Is that the problem? Could you test my configuration too?

**Comment by Patomosm** [comment]
Resolved!! It was the "Held Lighting Bright" option I had to Normal.
![Base Profile Screenshot 2023 06 03 - 16 22 43 21](https://github.com/sixthsurge/photon/assets/133518090/a3ec4d30-db31-4e96-b6b6-cc85b1ff6b2d)
![Base Profile Screenshot 2023 06 03 - 16 22 50 06](https://github.com/sixthsurge/photon/assets/133518090/1ee680e5-9956-4256-b4ae-25465ca27556)
![Base Profile Screenshot 2023 06 03 - 16 22 57 38](https://github.com/sixthsurge/photon/assets/133518090/b818bf15-8910-46b0-a59a-572f9c2f9dd1)
As you can see my avatar is inside a hole, to simulate the issue I talked about... hoping a workaround of "path tracing" results.
Doesn't work because the light passes through the walls.

**Comment by Xposeded** [comment]
> Resolved!! It was the "Held Lighting Bright" option I had to Normal. ![Base Profile Screenshot 2023 06 03 - 16 22 43 21](https://user-images.githubusercontent.com/133518090/243101978-a3ec4d30-db31-4e96-b6b6-cc85b1ff6b2d.png) ![Base Profile Screenshot 2023 06 03 - 16 22 50 06](https://user-images.githubusercontent.com/133518090/243102021-1ee680e5-9956-4256-b4ae-25465ca27556.png) ![Base Profile Screenshot 2023 06 03 - 16 22 57 38](https://user-images.githubusercontent.com/133518090/243102043-b818bf15-8910-46b0-a59a-572f9c2f9dd1.png) As you can see my avatar is inside a hole, to simulate the issue I talked about... hoping a workaround of "path tracing" results. Doesn't work because the light passes through the walls. **Is there a way to occluding held light source?** ... **_I think Yes, like sun light does proyecting shadows!_** Am I wrong? (sorry for my silly brainstorm)

It is possible, and there are various of ways to implement it. However, since I'm just a beginner, I'm currently not skilled enough to implement such algorithm.

**Comment by Patomosm** [comment]
Thanks Xposeded.
**I hope @sixthsurge will implement those stuff...**

I think I've resolved the difference between the option "Normal" and "Bright".
I've attached 2 files of yours with more defined colors inside, but I don't understand why the others than the 5th seem not working. Coud you check them up?
[item.zip](https://github.com/sixthsurge/photon/files/11643287/item.zip)

**Comment by Xposeded** [comment]
> Thanks Xposeded. **I hope @sixthsurge will implement those stuff...**
> 
> I think I've resolved the difference between the option "Normal" and "Bright". I've attached 2 files of yours with more defined colors inside, but I don't understand why the others than the 5th seem not working. Coud you check them up? [item.zip](https://github.com/sixthsurge/photon/files/11643287/item.zip)

The intensity of light relies on the value of "heldBlockLightValue" and "heldBlockLightValue2", which are decided by shader mod (Not shader pack). In that case, the value "heldBlockLightValue" of item "candle" is 0, so it won't emit any light. Here is the solution: reassign the "heldBlockLightValue" value when "heldItemId > 0 && heldBlockLightValue == 0" 
[diffuse.zip](https://github.com/sixthsurge/photon/files/11644721/diffuse.zip)

**Comment by Patomosm** [comment]
**Great! You do it!**
I wonder how it is possible to obtain such an intense color emission only for "held items" and not for normal blocks such as torches. I am not referring to the "Path Traced" effect but only to _the color saturation_, because now the differences are barely visible from very close (see my first post).
**Now I pray @sixthsurge to update his shaderpack with our modifications and enhanced hardcoded color emission blocks (torches and candles, for exemple) to match the item's ones.**
[item_diffuse.zip](https://github.com/sixthsurge/photon/files/11645580/item_diffuse.zip) - fixed Lime color.
Thanks Xposeded!

**Comment by Xposeded** [comment]
> **Great! You do it!** I wonder how it is possible to obtain such an intense color emission only for "held items" and not for normal blocks such as torches. I am not referring to the "Path Traced" effect but only to _the color saturation_, because now the differences are barely visible from very close (see my first post). **Now I pray @sixthsurge to update his shaderpack with our modifications and enhanced hardcoded color emission blocks (torches and candles, for exemple) to match the item's ones.** [item_diffuse.zip](https://github.com/sixthsurge/photon/files/11645580/item_diffuse.zip) - fixed Lime color. Thanks Xposeded!

Sadly, colored block lighting is way more complex than colored held lighting and will consume more performance. "The intensity of light is based on Minecraft's internal lightmap algorithm", as mentioned, Minecraft's lightmap provides only "light level (light intensity)", without any color data. So, the shader pack needs to find a way to distinguish different "colored light sources" which is not an easy goal to achieve. (At least not easy for a beginner, and that might be the reason why most shader packs don't provide colored block lighting feature.)

**Comment by sixthsurge** [comment]
hello,

I am planning to work on flood-fill coloured lighting once I'm done with exams, until then I'm taking a break from shader development to focus on revision

**Comment by Xposeded** [comment]
> hello,
> 
> I am planning to work on flood-fill coloured lighting once I'm done with exams, until then I'm taking a break from shader development to focus on revision

It's nice to hear about that, and good luck!

**Comment by Patomosm** [comment]
Useful links for you programmers:

https://github.com/LakMoore/Smooth-Entity-Light
https://www.curseforge.com/minecraft/mc-mods/smooth-entity-light

It is an old project but bringing good ideas, I think.

Waiting for updates, see you soon guys!

**Comment by sixthsurge** [comment]
Coloured flood fill lighting will be added as an option in the next commit
![2023-06-26_21 52 34](https://github.com/sixthsurge/photon/assets/61250625/19388bd1-3e67-4b1d-846a-13fc516b3386)

**Comment by Patomosm** [comment]
Sorry for reopening this issue... 
The option you added "Colored Lights" turned on is "invalid" with Optifine. Seam works only with Iris.

**Comment by sixthsurge** [comment]
yes, it requires Iris features that OptiFine doesn't support to work, so it only works on Iris

**Comment by Patomosm** [comment]
GREAT, YOU DO IT!
![Minecraft Screenshot 2023 06 28 - 18 14 52 23](https://github.com/sixthsurge/photon/assets/133518090/1461b958-2d47-413d-977f-ee1e3b721148)

I had to use "Fabulously Optimized" mod to be able to have Optifine features like connected features.
