### ISSUE TITLE
Armor trims are invisible when using this shader. (Iris)(MC 1.20)

### ISSUE THREAD

**Issue by allusive-dev** [sixthsurge/photon#15]

**Comment by allusive-dev** [comment]
I can confirm that this is the only shader affected so far.
Shaders Tested that work:
Seus Renewed
Complementary/ Reimagined
Sildurs Vibrant

**Comment by Patomosm** [comment]
Yes, I have the issue too, but only with Iris, not with Optifine.

OPTIFINE SCREENSHOT
![Base Profile Screenshot 2023 06 30 - 21 39 47 97](https://github.com/sixthsurge/photon/assets/133518090/9c2a74d6-3d4f-4ae0-9c73-0e0036c6b08f)

**Comment by IMS212** [comment]
This is fixed in Iris, will be in 1.6.5.

**Comment by NolanHewitt** [comment]
I still encounter this issue using iris 1.7.2
