### ISSUE TITLE
Light emitting blocks should emit light in hand

### ISSUE THREAD

**Issue by FormalSnake** [sixthsurge/photon#18]
Like LambDynamicLights, I have seen other shaders do this.

**Comment by sixthsurge** [comment]
the reason I don't add this is because I think it's better implemented by mods like lambdynamiclights, as those also make dropped items and entities emit light which is difficult to do in a shader

**Comment by Patomosm** [comment]
I tryed LambDynamicLight. Same issue of color type: they are not hardcoded but lightmapped.

**Comment by FormalSnake** [comment]
The thing is, the mod is not available in 1.20 and that is pretty annoying. I think complementary managed to implement this. But if it is too hard or unnecessary you can just close this issue.
No pressure.

**Comment by sixthsurge** [comment]
don't worry, it's not hard to implement at all
as I'm adding an option for coloured lights in the next commit, I will add an option for coloured handheld lighting to go with it

**Comment by sixthsurge** [comment]
added

**Comment by FormalSnake** [comment]
Nice!

**Comment by sixthsurge** [comment]
Did you make sure to enable Handheld Lighting in the Lighting menu too?

**Comment by FormalSnake** [comment]
yep
