### ISSUE TITLE
Armors get invisible

### ISSUE THREAD

**Issue by GitCodMaster** [sixthsurge/photon#193]
### What happened?

Please fix this issue, because this is my favourite shader yet and this problem makes every pro of the shader to a negative.
I am playing on 1.21 with Iris shaders

The Problem is that everytime a player is wearing a armor piece, that armor piece gets invisible
![2024-06-30_18 27 27](https://github.com/sixthsurge/photon/assets/158101468/3983d44a-e4eb-42e7-9e1c-0b957b821f80)

### Minecraft Version

1.21

### Which shader mod are you using?

Iris

### Shader mod version

1.0a

### Shader settings

```conf
AIR_FOG_COLORED_LIGHT_SHAFTS=true
BLOCK_ENTITY_SHADOWS=true
COLORED_LIGHTS=true
HANDHELD_LIGHTING=true
INFO=3
WATER_CAUSTICS=true
shadowMapResolution=4096
```

**Comment by 0609steve** [comment]
I encountered the same situation with you, check whether you have Shoulder Surfing Reloaded, I removed it to solve the problem

**Comment by GitCodMaster** [comment]
oh thank you. Still this is a issue of the shader that needs to be fixed

**Comment by GitCodMaster** [comment]
I found the Fix! You need to go into the config file of shoulder surfing and then set the adjust_player_transparency in line 113 to "false". thats it!
