### ISSUE TITLE
Werid texture when shaders are loaded (Using optifine 1.19.1)

### ISSUE THREAD

**Issue by Drakkkoo3344** [sixthsurge/photon#2]
All blocks are left with random colored texture in every block
![2022-08-15_11 02 47](https://user-images.githubusercontent.com/111300490/184671889-e47af309-67cb-44a8-97b1-5b1560855ab6.png)

**Comment by sixthsurge** [comment]
This is an issue with OptiFine H9 which affects all shader packs, the fix is to switch to OptiFine H8.
