### ISSUE TITLE
Water Refraction is not Working Correctly

### ISSUE THREAD

**Issue by tunaflsh** [sixthsurge/photon#204]
### What happened?

A common property of water refraction is that the bottom of a pool appears closer than it actually is. In these two images we can see no difference between refraction being turned on and off. Note that I have waves turned off.

![refraction off](https://github.com/user-attachments/assets/6681f570-2a06-41cc-83d1-0c2bc0f76eec)
![refraction on](https://github.com/user-attachments/assets/623e56a9-80ad-4e10-bda2-2affa06925dc)

### Minecraft Version

1.20.2

### Which shader mod are you using?

Iris

### Shader mod version

1.7.3+mc1.21

### Shader settings

```conf
#Sat Jul 27 00:50:56 CEST 2024
AIR_FOG_COLORED_LIGHT_SHAFTS=true
AIR_FOG_MIE_DENSITY_BLUE_HOUR=0.0025
AIR_FOG_MIE_DENSITY_EVENING=0.0020
AIR_FOG_MIE_DENSITY_MIDNIGHT=0.0003
AIR_FOG_MIE_DENSITY_MORNING=0.0020
AIR_FOG_MIE_DENSITY_NOON=0.0003
AUTO_EXPOSURE=AUTO_EXPOSURE_HISTOGRAM
BLOCKLIGHT_I=2.00
BLOCK_ENTITY_SHADOWS=true
BLOOMY_FOG=false
BLOOM_INTENSITY=1.01
CAVE_LIGHTING_I=1.45
CLOUDS_SCALE=1.0
CLOUDS_TEMPORAL_UPSCALING=1
DOF_INTENSITY=0.20
DOF_SAMPLES=10
HANDHELD_LIGHTING=true
HISTOGRAM_TARGET=0.6
SH_SKYLIGHT=true
VANILLA_SUN=true
VIGNETTE=false
WATER_CAUSTICS=true
WATER_FOAM=true
WATER_REFRACTION_INTENSITY=2.00
WATER_WAVES=false
shadowDistance=768.0
```

**Comment by sixthsurge** [comment]
Hello, 

While the realistic refraction like you describe looks very cool, it's not really possible with the fake, screen space refraction method Photon uses and wouldn't even work well with proper screen-space ray tracing; full on world-space RT would be required to do this well which is beyond the feature and performance scope of Photon

**Comment by tunaflsh** [comment]
I see that makes sense.
