### ISSUE TITLE
Sun seen from underwater

### ISSUE THREAD

**Issue by Patomosm** [sixthsurge/photon#21]
Please look at the video clip. This is a new issue that wasn't before right in the last version.

https://github.com/sixthsurge/photon/assets/133518090/916ee082-1757-4168-a6c2-ea8ef0a17448

My enabled shader options:
[photon-main.zip.txt](https://github.com/sixthsurge/photon/files/11824628/photon-main.zip.txt)

However, I must point out the following:
_ now I'm using "preview OptiFine 1.20.1 HD U I5 pre4" while before I used "OptiFine HD U I4"
_ now I'm using "Forge 1.20.1-47.0.3"
_ when it worked well I still used versions 1.19.4

**Comment by Merlin1809** [comment]
I have the same issue with 1.18.2 and oculus. All iris compatible versions seem to have this problem. Can't test earlier versions though.

**Comment by FormalSnake** [comment]
The only underwater issue I have is that the light rays are very quick.

**Comment by sixthsurge** [comment]
Hi, were you using Physics Mod in this clip?

**Comment by Patomosm** [comment]
I don't remenber but I tested again without Physisc Mod and **I confirm the issue.**

Also I add another clip with **weird moon reflection at falling water**. Maybe is the same issue, maybe not ...

https://github.com/sixthsurge/photon/assets/133518090/b69e23ef-a12b-4d86-881b-34e3c3af1cf9

**Comment by sixthsurge** [comment]
Fixed in the latest commit
