### ISSUE TITLE
"Handheld lighting" color option.

### ISSUE THREAD

**Issue by Patomosm** [sixthsurge/photon#23]
Sorry for reopening this issue...
The option you added "Colored Lights", when turned on crashes "invalid" with Optifine. The screen message says that it works only with Iris.
Will you fix that?

**BEFORE**
![Base Profile Screenshot 2023 06 28 - 16 55 22 52](https://github.com/sixthsurge/photon/assets/133518090/6ad83dc4-58d1-4268-8f2b-63047d8409aa)

**AFTER**
![Base Profile Screenshot 2023 06 28 - 16 55 49 84](https://github.com/sixthsurge/photon/assets/133518090/6f1a39fc-b442-4a0e-9975-df642b065f67)

**Comment by sixthsurge** [comment]
No, as it says on that error screen I made, the option requires Iris features that OptiFine does not support to work, so I can't make it work on OptiFine
