### ISSUE TITLE
Galaxies 🙏🥺

### ISSUE THREAD

**Issue by LWestTech** [sixthsurge/photon#238]
### Description

I would LOVE to see some galaxies/nebulae as an option for the night sky. Especially because your northern lights look so good, I bet you guys would make it look STUNNING. I think Complementary Unbound has an option for this, but I much prefer your shader especially for the clouds. Part of the point of this is that the northern lights are amazing, but it doesn't make sense for them to be there all the time, and if you keep it on always, the novelty will wear off. That being said, the night sky looks absolutely gorgeous with all of the added color, and so one easy and objectively awesome/beautiful ways to do that but more subtly would be to add galaxies/nebulae that are always out regardless of the biome.

For more flavor you could have the brightness be tied to a sample of the local cloud cloud coverage so that when the skies are clear, you can see it really well, but it won't busy up the sky or filter unrealistically through the clouds if its cloudy.

What I mean by galaxies/nebulae is specifically like how we can see the milky way galaxy in the sky at night, just I would expect it to be a bit more colorful and stylized 

Here are some stock images I found online to get you excited about this feature idea:

![image](https://github.com/user-attachments/assets/8de7fdd6-04ae-4088-a054-438415cb5ee7)
![image](https://github.com/user-attachments/assets/406f6381-df8b-4130-82d4-8e55da03d83c)
![image](https://github.com/user-attachments/assets/4d72f59c-456d-413d-adf4-3a41a658480f)
![image](https://github.com/user-attachments/assets/ada64e0d-2720-4a6a-a2e1-39f00a00a53a)
![image](https://github.com/user-attachments/assets/0b70475a-b07e-4fad-9683-8f4ae096a39b)
![image](https://github.com/user-attachments/assets/1305f8d7-87cb-405b-859c-35b0a73ac37d)
![image](https://github.com/user-attachments/assets/29f89619-dffd-4211-9a3c-2b01372f57f4)

**Comment by sixthsurge** [comment]
try the dev branch and you will be happy

**Comment by LWestTech** [comment]
I downloaded the latest commit from the dev branch but no galaxies 😭

![image](https://github.com/user-attachments/assets/419a9b3d-8010-4329-bf61-e8124dd58acb)

I also tried resetting the settings to default but it still didn't show up

**Comment by LWestTech** [comment]
I didn't see a setting for it anywhere either so is it possible that I downloaded the wrong thing?
I set the branch to dev and clicked the "download latest commit" link in the README

**Comment by LWestTech** [comment]
Ok now I manually downloaded the branch as a zip, but it still isn't showing up ingame or as a setting

**Comment by sanshz** [comment]
Its in photon-dev

![image](https://github.com/user-attachments/assets/4e4ef30c-3496-49d4-a8d8-34cacc0691e4)

**Comment by LWestTech** [comment]
![image](https://github.com/user-attachments/assets/6b863962-d2a6-4747-83c5-0e0cdc016338)

Found it, thanks!!!!!!!!! Yeah, I thought for sure I had downloaded the branch but considering the pack was named photon-main I should have realized that I accidentally downloaded the main not the dev branch 🤷

**Comment by GitCodMaster** [comment]
what do you guys mean with the brench? i want galaxies too but the galaxy setting isnt showing up.

**Comment by sanshz** [comment]
First on photon repo, change branch from main to dev

![image](https://github.com/user-attachments/assets/c9691e1a-5f66-4b81-85d9-4a42f7e482fc)

Then just click green code button and press 'download zip". You will get 'photon-dev'
