### ISSUE TITLE
Particle's color

### ISSUE THREAD

**Issue by Patomosm** [sixthsurge/photon#27]
I refer to this type of particles (square Vanilla style):
1_ underwater they should be cyan, but they are pink
2_ in soul_sand_valley they should be light brown but are dark;
3_ in warped_forest are dark (Java) but would be more beautiful blue (as in Bedrock).

Perhaps that is not very important, since they would be non-reflective matter and their color would not be evident if not near a light source but... It would be nice if they were more noticeable like in basalt_deltas (gray) and crimson_forest (pink).

**Comment by Patomosm** [comment]
...Ok, I've found particle's texture: \minecraft\textures\particle\generic_0.png.
His color is white or barely gray, so the color it takes on biomes depends on Minecraft, regardless of shaders, I think.
I tried to better illuminate an area of the nether biomes and the color taken shows better.
_ in soul_sand_valley they are brown,
_ in warped_forest they are dark blue.
The only "anomaly" to report is the crimson_forest particle, which always shows light pink even without lighting.

What do you think, are you able to assign the desired color through the shader?
If it is not possible, don't mind, you can close the issue.

**Comment by sixthsurge** [comment]
Currently I don't know of a good way to detect different kinds of particles in the shader, but there is a potential Iris feature that has been discussed that would make this possible. Until then, adjusting the colour of each type of particle is not possible
