### ISSUE TITLE
Skybox doesn't seem to move with the head bobbing

### ISSUE THREAD

**Issue by EsserGaming** [sixthsurge/photon#29]
I do have a few mods that modify the first person view but I'm not sure if it's because of that.

GPU: RX 7900XT
Drivers: 23.5.2 (Latest at the time, known to have issues)

The video for it:
https://cdn.discordapp.com/attachments/887496194237026324/1124855812725153903/2023-07-01_19-13-58.mp4

**Comment by Patomosm** [comment]
The head is represented by the camera, which oscillates to the rhythm of the steps.
Shifting the gaze also shifts the landscape, including the skybox.
**Really, I can't understand this issue.**

https://github.com/sixthsurge/photon/assets/133518090/aca51ecb-aa96-4b74-a7d0-77b7e9d4976b

I don't see any oddities in your video and mine.
