### ISSUE TITLE
Armor Trims

### ISSUE THREAD

**Issue by DillPickle66** [sixthsurge/photon#32]
You can't see armor trims while using the shader.
With Photon:
![2023-07-08_16 51 45](https://github.com/sixthsurge/photon/assets/136403943/37777ef6-d781-4b40-8791-12435ec9db0a)
With Complimentary Reimagined:
![2023-07-08_16 53 14](https://github.com/sixthsurge/photon/assets/136403943/d74367f9-3b15-4b73-8e73-5eb06608a27a)

**Comment by sixthsurge** [comment]
Hi, this will be fixed with the next Iris update
