### ISSUE TITLE
Lava flowing diagonally   --AND--   Field of View (FOV)

### ISSUE THREAD

**Issue by Patomosm** [sixthsurge/photon#34]
**Same screenshot from same position with FOV 75 in Minecraft Options.**

PHOTON SHADER
![Minecraft Screenshot 2023 07 10 - 21 44 23 99](https://github.com/sixthsurge/photon/assets/133518090/fe883018-f275-4c8c-a665-8ea570732bd0)

COMPLEMENTARY SHADER 4.7.2
![Minecraft Screenshot 2023 07 10 - 21 44 51 58](https://github.com/sixthsurge/photon/assets/133518090/59b83f15-aeff-4836-9e9b-f1e7d7c7ebe6)

**Comment by sixthsurge** [comment]
Fixed

**Comment by Patomosm** [comment]
About the FOV... I checked it is a Complementary Shader Issue.
