### ISSUE TITLE
Shadow Bug

### ISSUE THREAD

**Issue by 881613** [sixthsurge/photon#35]
Please fix the bug that occurs when the shadow drawing distance is changed, which causes the resolution of the shadow to decrease.

Shadowdistance 4chunk
![2023-07-15_12 09 20](https://github.com/sixthsurge/photon/assets/139604011/cc1c3204-ffef-4616-824e-ff9708e0ec60)

Shadowdistance 64chunk
![2023-07-15_12 09 06](https://github.com/sixthsurge/photon/assets/139604011/0e967429-b289-423c-8b9f-30300673c20d)

**Comment by sixthsurge** [comment]
this isn't a bug, the shadow map is spread over a larger area so the resolution appears lower
