### ISSUE TITLE
What are the supported game versions?

### ISSUE THREAD

**Issue by BryanLiu29** [sixthsurge/photon#37]
What are the supported game versions? I ran it on 1.12.2 and game crashed.
![image](https://github.com/sixthsurge/photon/assets/140695043/f84c5d5b-9f59-4f37-a87f-13aa13dfa89d)

**Comment by Patomosm** [comment]
Currently the latest version of Minecraft Java edition is 1.12.1.
Version 1.12.2 is some sort of fake, perhaps a virus-hacked version.
Check it!

**Comment by sixthsurge** [comment]
The oldest supported version is currently 1.16.5 - I'm planning to see if I can make it work down to 1.12.2 soon

Pantomosm - Minecraft is currently on 1.20.1, 1.12.2 is very old

**Comment by Patomosm** [comment]
Ooops! I misunderstood the number 12 with 20 ... 
It doesn't seem credible to me that there is still someone playing such an old version!
Sorry to BrianLiu29.

**Comment by BryanLiu29** [comment]
> Ooops! I misunderstood the number 12 with 20 ... It doesn't seem credible to me that there is still someone playing such an old version! Sorry to BrianLiu29.

Well, if you want to enjoy mods like Twilight Forest and Project E, there are't many new versions to choose from...

**Comment by BryanLiu29** [comment]
> The oldest supported version is currently 1.16.5 - I'm planning to see if I can make it work down to 1.12.2 soon
> 
> Patomosm - Minecraft is currently on 1.20.1, 1.12.2 is very old

Got it. It seems I'll have to wait for a while. 😂

**Comment by BryanLiu29** [comment]
> Ooops! I misunderstood the number 12 with 20 ... It doesn't seem credible to me that there is still someone playing such an old version! Sorry to BrianLiu29.

Well, I haven't really played the game since 1.15, so it's hard to keep up with the recent updates. And with all my saves and mods tied to 1.12, I just simply stick to it.

**Comment by Patomosm** [comment]
Do you need help to update? My suggestions to do a try:
0_ go to save folder and back up your worlds;
1_ download the combination you use for supporting shaders, Optifine+Forge or Iris+Fabric according to mods version you find in step 2;
2_ go to courseforge.com in searching for each mod you used in the past (if exsisting yet) and download the latest (same) version, hoping you'll find 1.20 to all of them;
3_ Install choosen combination into Minecraft install path;
4_ open mod folder and paste your new jar mod files;
5_ open shader folder and paste photon shader;
6_ run Minecraft, set it up and enjoy.

**Comment by Patomosm** [comment]
Pay attention to:
step 3_ if all goes well you will not loose older installations but you'll find them listed together;
step 4_ before pasting new mods you have to create a folder where moving older ones.

**Comment by BryanLiu29** [comment]
> Do you need help to update? My suggestions to do a try: 0_ go to save folder and back up your worlds; 1_ download the combination you use for supporting shaders, Optifine+Forge or Iris+Fabric according to mods version you find in step 2; 2_ go to courseforge.com in searching for each mod you used in the past (if exsisting yet) and download the latest (same) version, hoping you'll find 1.20 to all of them; 3_ Install choosen combination into Minecraft install path; 4_ open mod folder and paste your new jar mod files; 5_ open shader folder and paste photon shader; 6_ run Minecraft, set it up and enjoy.

Thanks a lot. But I hadn't played the game for 6 or 7 years untill I did resently. So with more than half a dozen versions left behind, I really haven't got the time to figure out what's new in these years nor to start up a whole new survival save. But thanks anyway bro, I haven't seen many people as helpful and authentic as you for perhaps a decade on the Internet.
