### ISSUE TITLE
Armor trim does not render

### ISSUE THREAD

**Issue by zivoric** [sixthsurge/photon#39]
Armor trim is not rendering with the shaders on. I am using running Fabric 1.20.1 with Iris.
Here is with the shader on:
![image](https://github.com/sixthsurge/photon/assets/52415929/c6a931a6-1058-4ae2-a0a3-e33febb09ed4)
And shaders off:
![image](https://github.com/sixthsurge/photon/assets/52415929/16974d29-2fa6-4384-9a60-4aec45d33fdb)

**Comment by sixthsurge** [comment]
Iris issue, will be fixed in Iris 1.6.5

**Comment by Patomosm** [comment]
Now it works.
