### ISSUE TITLE
Handheld lighting stops working at 30k+ coords

### ISSUE THREAD

**Issue by zivoric** [sixthsurge/photon#45]
As soon as the player hits 30k+ in the world, handheld lighting stops working, even if the player returns to lower coordinates. See this happening in the video below:

https://github.com/sixthsurge/photon/assets/52415929/8bf4b90f-6f9b-4f3d-ab4f-e482294dd177

Reloading shaders seems to fix the problem if you return to lower coordinates (sub-30k), but if you are at above 30k, reloading shaders does not fix and handheld lights don't seem to work at all.

I am using Iris 1.6.7 and the latest photon from the repository.

**Comment by Spokzooy** [comment]
I also have this problem.
Iris 1.6.8

**Comment by Patomosm** [comment]
I don't want to seem impatient but... Why would a player want to go so far away in any world?
I promise that one day I will try too but, honestly, I do not believe that the impact of this issue is really compromising on the gaming experience along with any shader pack.

**Comment by zivoric** [comment]
> I don't want to seem impatient but... Why would a player want to go so far away in any world?
> 
> I promise that one day I will try too but, honestly, I do not believe that the impact of this issue is really compromising on the gaming experience along with any shader pack.

Sure, isn't really a huge issue, but there are plenty of people that go beyond 30k coords when playing, especially on larger servers.

**Comment by tsumi7** [comment]
With Iris 1.18.2 and https://github.com/sixthsurge/photon/commit/46c57567b436722669b459bf14d9eb7c19d18e86, this is now fixed.
