### ISSUE TITLE
Weird shadow issues on Ultra preset and my custom settings

### ISSUE THREAD

**Issue by R2-iDiot2** [sixthsurge/photon#46]
![image](https://github.com/sixthsurge/photon/assets/96367432/e8a32043-165f-458b-9819-156fc09158b6)
![image](https://github.com/sixthsurge/photon/assets/96367432/6931944e-7dd6-4219-b957-71a177bc6f92)
Weirdly enough this is fixed on the High preset
![image](https://github.com/sixthsurge/photon/assets/96367432/ddaf2f9c-4c4b-47d8-b3b7-57b4ac2fba5a)
What setting should I disable to get rid of this?

**Comment by xlifi** [comment]
> What setting should I disable to get rid of this?

Colored lights, wierdly enough. Should probably keep this open, but rename to something like "Colored lights behaving incorrectly"

**Comment by xlifi** [comment]
> I am not sure that this issue can be called common.  I always use the settings to "ultra" and even more with customization, but I do not have this problem.
> Some issues arise from the hardware configuration you use, such as issue #42, although they should not be considered justified.
> Let's wait for @sixsurge to have his say.

Do you have colored lights enabled? And what's your GPU vendor, driver version and OS version?

Mine is 
GPU: nVidia RTX 3060
Driver: GeForce Game Ready 536.99 (going to test on 537.13 later)
OS: Windows 11 22621.2134

**Comment by Patomosm** [comment]
Ok, I did other tests and actually **you were right**, but the issue has a close relationship with all kinds of carpets (wool and moss), regardless of any texture package.
I tried other shaders and they do not seem to show the same light effect with carpets.
My conclusion is: **ultra photon lighting with carpets show a light scattering bug on them.**

**Comment by Steakob97** [comment]
Yes this is the voxelised lighting system photon uses for its coloured lighting working incorrectly. It is assuming certain shapes about the carpets that are not correct. As other presets use a different lighting system, you will not see this issue with those. You should also see the bug disappear when you walk a certain distance away from the carpet (this might be quite far).

**Comment by Patomosm** [comment]
Another example but to the moss carpets in a lush cave, illuminated by lava.

![Base Profile Screenshot 2023 10 17 - 18 54 23 16](https://github.com/sixthsurge/photon/assets/133518090/ecc6134a-b464-4ebd-ac1f-3b19cf74c595)

**Comment by Patomosm** [comment]
It happens with Nether Wart too. Blocks the light.

**Comment by Patomosm** [comment]
Not fixed yet, despite handheld_lighting.glsl update.
![Base Profile Screenshot 2024 02 26 - 23 56 11 41](https://github.com/sixthsurge/photon/assets/133518090/8ec6b0f1-13c3-49ac-b790-09b1a70cb0a3)
You can see carpets and nether warts covered by wrong shadows.

**Comment by Patomosm** [comment]
![Base Profile Screenshot 2024 02 28 - 19 20 22 01](https://github.com/sixthsurge/photon/assets/133518090/df5f83c2-c5a8-489f-8fc5-98b49a00ecf3)

**Comment by Patomosm** [comment]
I fixed this issue and issue #106. Download the file to follow.
[photon-main.zip](https://github.com/sixthsurge/photon/files/14474334/photon-main.zip)

**Comment by sixthsurge** [comment]
fixed
