### ISSUE TITLE
Dark sky

### ISSUE THREAD

**Issue by Touma-Kazusa2** [sixthsurge/photon#49]
I can't be sure if it's because of certain settings that have caused this situation, When I stand beneath some large buildings, the sky darkens（Or should I say, the distance becomes very dark?）. Additionally, under this shader, my resourcepack for the skybox seems to have become invalid, luckily, the current sky looks good enough.
![2023-09-02_01 14 15](https://github.com/sixthsurge/photon/assets/126475460/d24bbe59-7c4d-4652-92ce-43471e448103)
![2023-09-02_01 14 24](https://github.com/sixthsurge/photon/assets/126475460/d07e144f-326a-4c1c-826b-7afd9ff27859)

**Comment by Steakob97** [comment]
The sky darkening is the shader preventing light leaking. If you were in a large cave and it did not do this you would end up with very bright spots where the rendered world ends. There may be a setting to turn this off, some shaders do have it, but I don't know where you would find it and I can't check right now. The resourcepack not showing up is pretty normal, and again some shaders have the option to allow custom skyboxes but I'm not sure if photon does or not. I would recommend digging through the settings to find anything related to skyboxes or light leaking. Hope this helps.

**Comment by Patomosm** [comment]
I found this.

![Base Profile Screenshot 2023 09 01 - 21 23 23 73](https://github.com/sixthsurge/photon/assets/133518090/b53143dd-9653-451b-92b0-589924e65697)

I think light leaking is enabled by default.

**Comment by Steakob97** [comment]
Yeah photon might not have the option to disable the anti light leaking, and that does appear to be the setting to enable custom skyboxes. I seem to remember trying the dramatic skies texture pack and enabling that setting but it did nothing, however idk it might work for you.

**Comment by Touma-Kazusa2** [comment]
Oh,i get it,i conducted a test and discovered that it only occurs when the player is below y = 50, so in most cases, this won't occur unless the world type is set to superflat and there is a large building present.
I tried enabling the custom skybox setting, but it didn't work. Nevertheless, the presence of this setting may imply that there is a way to enable a custom skybox, however, i haven't found that method. The reason it not work could be because I'm using iris instead of optiFine. I haven't tested it yet, so I'm not sure.

**Comment by Touma-Kazusa2** [comment]
Although this might make me seem a bit clueless, I wanted to say that I've found the custom skybox working. Thanks for your assistance! Photon is an excellent shader.
