### ISSUE TITLE
how do i download?

### ISSUE THREAD

**Issue by bananaOHHHOOOOHAHAHAHAAAAHA** [sixthsurge/photon#5]
yeah how do i download? there are no packages and i dont think theres anyway to download the files

**Comment by sixthsurge** [comment]
Hi, normally you would download it by pressing the big green Code button and then clicking "Download zip", however just for you [here's](https://github.com/sixthsurge/photon/archive/refs/heads/main.zip) a link to download the version on the main branch and [here's](https://github.com/sixthsurge/photon/archive/refs/heads/rework.zip) a link to download the version on the rework branch (the version I'm working on at the moment!)
