### ISSUE TITLE
Texture error in the End

### ISSUE THREAD

**Issue by ItIsNotAPlayer** [sixthsurge/photon#51]
Terrain texture is white in the end dimension.
![2023-09-09_02 26 58](https://github.com/sixthsurge/photon/assets/102716584/6b6648d3-5c46-4e93-8ae7-a64f161a6193)
![2023-09-09_02 29 33](https://github.com/sixthsurge/photon/assets/102716584/3f142507-0099-4c44-84c6-1a8486ee062d)

**Comment by Patomosm** [comment]
I don't have the issue. I'm playing with Iris.

![Base Profile Screenshot 2023 09 09 - 14 13 54 70](https://github.com/sixthsurge/photon/assets/133518090/8f0ae25d-6b5b-457b-b4ff-7bacedbe1c52)

A question to you: are you playing with Optifine? If yes, remember that Optifine does not support "Colored lights" settings.

I think your issue may have a connection with issue #42 if you have a low level hardware machine or an integrated gpu.

**Comment by ItIsNotAPlayer** [comment]
Maybe it's because of my GPU. It is Intel HUD Garphics.
If I use Iris, the shaderpack doesn't work in the end and I got this:
`hand_translucent.vsh: hand_translucent.vsh: ERROR: 0:55: 'assign' :  cannot convert from 'const int' to 'varying highp uint'`

**Comment by ItIsNotAPlayer** [comment]
This bug has been fixed in the latest version.
