### ISSUE TITLE
Help!!!

### ISSUE THREAD

**Issue by Y3Shua12** [sixthsurge/photon#53]
Hi, I love this shader, but I have some problems, please help me.

Im playing mods, i share a capture.

![imagen_2023-09-09_212219633](https://github.com/sixthsurge/photon/assets/144575010/6ea4bcfc-33af-43cf-b1a5-825a717b6338)

it only happens with this mod

**Comment by BitinAnty** [comment]
whats the mod

**Comment by Y3Shua12** [comment]
> 
Ty 
Epic Fight

**Comment by Patomosm** [comment]
The mod is still at version 1.18.2 and is only compatible with the Forge loader (do you use Iris?).
Too many good reasons not to work!

**Comment by Y3Shua12** [comment]
> whats the mod
Epic fight
Version: 1.18.2

**Comment by Y3Shua12** [comment]
> The mod is still at version 1.18.2 and is only compatible with the Forge loader (do you use Iris?). Too many good reasons not to work!

Yeah, its 1.18.2 
Im using Rubidum and Oculus

**Comment by Ray-Dieterich** [comment]
I have resolved it. Just modify your 'epicfight-client.toml' in your config folder, and set 'health_bar_show_option = "NONE"'.

**Comment by Y3Shua12** [comment]
thank you so much
