### ISSUE TITLE
Night Shader Exception！

### ISSUE THREAD

**Issue by 3037342271** [sixthsurge/photon#55]
![屏幕截图 2023-09-15 154912](https://github.com/sixthsurge/photon/assets/69409504/796ac9f1-e758-44a4-86ec-99a569104adc)
在夜晚的时候会出现类似北极光的效果，但是颜色是黄色的，并且整个世界被蒙上了一层黄色的滤镜...
At night, an effect similar to the Northern Lights appears, but the color is yellow and the entire world is covered with a yellow filter...

**Comment by NakiriRuri** [comment]
这是正常表现，这是作者特意做的功能：北极光的颜色会影响云层照明和地形照明；你如果不想这样的话，可以在光影设置里关掉；
具体设置位置：视频设置-->光影包-->Photon-->光影包设置-->Sky-->Aurora，不想云层照明受影响就把 Cloud Light Contribution 滑块拉到 0.00，不想地形照明受影响就把 Ground Light Contribution 滑块拉到 0.00。

**Comment by 3037342271** [comment]
感谢讲解，这就去修改
