### ISSUE TITLE
deferred3.fsh: deferred3.fsh: 0(1618) : error C1503: undefined variable "parallax_shadow"

### ISSUE THREAD

**Issue by BlackRiceXY** [sixthsurge/photon#59]

**Comment by sheikh1233** [comment]
are you able to provide more details than just the title
like what mod loader, shader loader, etc

**Comment by Patomosm** [comment]
Please attach here your "photon-main.zip.txt" file (in shader folder) to let @sixthsurge check the options combination.

**Comment by BlackRiceXY** [comment]
sodium-fabric-mc1.20.2-0.5.3
iris-mc1.20.2-1.6.9

I just turned on Parallax Occlusion Mapping in Materials.

photon-main.zip.txt：
#Sun Oct 08 22:44:06 CST 2023
POM=true

**Comment by Patomosm** [comment]
I enabled POM too but I don't have the issue.
I'm playing with version 1.20.1 and Iris 1.6.9.

**Comment by BlackRiceXY** [comment]
> I enabled POM too but I don't have the issue. I'm playing with version 1.20.1 and Iris 1.6.9.

So I don't know why iris prompted an error and asked me to copy this message to the developer

**Comment by tsumi666** [comment]
On the latest version of Photon a settings file with only `POM=true` appears to build, however it likely doesn't do anything as POM requires normal mapping enabled to operate correctly.

Please test again and reopen if it's still an issue.
