### ISSUE TITLE
Moon rendering is broken

### ISSUE THREAD

**Issue by XDom367** [sixthsurge/photon#60]
![image](https://github.com/sixthsurge/photon/assets/126047992/90dd0808-aca2-44a7-a68e-53472ca08b10)
The moon isn't rendering in.
Iris 1.6.10 sodium 0.5.3

**Comment by XDom367** [comment]
[photon-main1.zip.txt](https://github.com/sixthsurge/photon/files/12902046/photon-main1.zip.txt)

**Comment by Patomosm** [comment]
This issue is the same of #38, I think.
You were in new moon fase.

**Comment by XDom367** [comment]
It was actually an incompatibility with the [Dark mode Everywhere}(https://modrinth.com/mod/dark-mode-everywhere) mod. Forgot to comment on this, apologies.
