### ISSUE TITLE
when use this shader,the game crashed

### ISSUE THREAD

**Issue by Maxdontron** [sixthsurge/photon#63]
the game version is 1.20.1,i have no idea with the crash report,
i'm using fabric, the mods may caused the problem,but i'm not sure
or maybe the iris version is not available with this shader?

**Comment by Patomosm** [comment]
Perhaps Your Java installation is broken. Try to
1. uninstall your current Java
2. reboot windows
3. download and install [this one](https://adoptium.net/temurin/releases/?version=17&os=windows&arch=x64&package=jdk) ; version 17; ENABLE ALL THE INSTALLATION FEATURE!
4. restart Minecraft

**Comment by Maxdontron** [comment]
> Perhaps Your Java installation is broken. Try to
> 
> 1. uninstall your current Java
> 2. reboot windows
> 3. download and install [this one](https://adoptium.net/temurin/releases/?version=17&os=windows&arch=x64&package=jdk) ; version SDK 17; ENABLE ALL THE INSTALLATION FEATURE!
> 4. restart Minecraft

should i upload the report?
[hs_err_pid3104.log](https://github.com/sixthsurge/photon/files/13116942/hs_err_pid3104.log)

**Comment by sheikh1233** [comment]
are you using iris and optifine at the same time
they are incompatible 
optifine isn't even on fabric

**Comment by Patomosm** [comment]
Try to start minecraft in vanilla standard mode, without mods and without shader. Do you have issues? If not, your java installation is ok.
Then restart with nothing but Iris+Fabric. If you have issues, try to reinstall Iris+Fabric, if not you can add one mod at a time to reveal the broken one (then download that again).

**Comment by Maxdontron** [comment]
> are you using iris and optifine at the same time they are incompatible optifine isn't even on fabric

no,i know they are incompatible,i just have iris

**Comment by Maxdontron** [comment]
> Try to start minecraft in vanilla standard mode, without mods and without shader. Do you have issues? If not, your java installation is ok. Then restart with nothing but Iris+Fabric. If you have issues, try to reinstall Iris+Fabric, if not you can add one mod at a time to reveal the broken one (then download that again). Beware at the versions! Must match all together.

minecraft in vanilla mode can work well.but iris+fabric have this problem,i have tried to reinstall iris and fabric,it still crashed
![Screenshot 2023-10-25 184258](https://github.com/sixthsurge/photon/assets/91769391/95cedf29-b1c6-402a-9e83-e8297cbcf59e)
this is the error report from my launcher,and i found the key sentences.i think the highlight sentence is important,so i followed its guide,i didn't know next photo if i can modify it
![Screenshot 2023-10-25 184202](https://github.com/sixthsurge/photon/assets/91769391/8b4fcd60-7cc5-4d20-a6aa-5db26e8c7164)
next step,how should i do

**Comment by Maxdontron** [comment]
> Try to start minecraft in vanilla standard mode, without mods and without shader. Do you have issues? If not, your java installation is ok.
> Then restart with nothing but Iris+Fabric. If you have issues, try to reinstall Iris+Fabric, if not you can add one mod at a time to reveal the broken one (then download that again).
> Beware at the versions! Must match all together.

my bad,i have solve the issue.the reason is that my gpu driver is not up to date
