### ISSUE TITLE
Enhanced visuals compatibility issue 

### ISSUE THREAD

**Issue by Maxion38** [sixthsurge/photon#64]
With the enhanced visuals mod installed, when going in water the screen turn black for a few seconds. Fixed if enhanced visual's splash effect is disabeled

**Comment by Patomosm** [comment]
[The description of that mod](https://modrinth.com/mod/enhancedvisuals) says: "... Fast Render, Anisotropic Filtering and Antialiasing has to be turned off. Otherwise your screen will turn black when certain effects are active."

**Comment by Maxion38** [comment]
oh okay my bad thx
