### ISSUE TITLE
Setting descriptions? and fog distance?

### ISSUE THREAD

**Issue by JusVale** [sixthsurge/photon#67]
I think adding simple setting descriptions would be helpful for people who dont understand much about them. Kinda how Complimentary have it, idk anyhting about coding but i figure it shouldnt be super hard but lil time consuming.
Theres many settings i have no clue about so i end up just turning them on and off to see if anything changes lmao.

Also, couldnt find a way to increase/decrease fog distance. if its not possible, theres this mod called ''simple fog'' that got simple configuration on fog, begin distance and end distance (percent of view distance), think something like that added would be cool. (this mod stops working when any shader is turned on, otherwise id just use it)

**Comment by sixthsurge** [comment]
There already are descriptions for most settings but they're in settings.glsl rather than the lang file (this worked on OptiFine but not on Iris)

**Comment by sixthsurge** [comment]
moved would be perfect, thanks

**Comment by JusVale** [comment]
thx ill try those settings out in a bit. not exactly how i was thinking but it might work. i was thinking like i wanna control how farm/close the fog starts, that way i can edit it according to the builds. like if 2 builds are rly far away then id set the fog start distance further so its more visible, or if the builds are closer id set it closer so the fog is still affecting it but not too much.

btw yall got a discord or something? would be easier for ppl to drop by and ask questions or help or anything over there

Also, paintings & item frames dont seem to work
![image](https://github.com/sixthsurge/photon/assets/149630676/d41c955b-ca95-484d-9b5b-7d1cfc779a9d)
![image](https://github.com/sixthsurge/photon/assets/149630676/8b42a876-a5b2-4949-9e81-2cb3cd8cbb42)

**Comment by tsumi666** [comment]
There is a channel for Photon in the [ShaderLABS discord](https://discord.gg/RpzWN9S). Could you make a new issue for the item frames and include your shader settings .txt and the resource pack you're using? I'm going to close this as #69 was merged so the descriptions should show up properly now.
