### ISSUE TITLE
[suggestion] torch emitting light when in hand

### ISSUE THREAD

**Issue by DarkPlayerr** [sixthsurge/photon#7]
would love to see torches being able to emit light when in hand, besides that i love the shaders. great job!

**Comment by sixthsurge** [comment]
Hello, if you are using Iris, the fabric mod LambDynamicLights adds this feature as well as emitted light from dropped items. If you are using OptiFine you just have to enable Dynamic Lighting in Video Settings :)

**Comment by DarkPlayerr** [comment]
thanks, works great.
closing this
