### ISSUE TITLE
Make End Rod lighting purple

### ISSUE THREAD

**Issue by Kinda-Stormy** [sixthsurge/photon#78]
### Description

I think it would make the world more vibrant.
I tried it out in a hacky way by setting end rods to have the froglight color

![image](https://github.com/sixthsurge/photon/assets/80485413/e0b9cded-8aeb-42ac-b99f-23ae9ffb6368)
![image](https://github.com/sixthsurge/photon/assets/80485413/94547e0b-ee41-425c-9046-4db48fbb777e)

**Comment by Patomosm** [comment]
I think your proposal does not appeal to those who prefer not to pollute too much original choices of Vanilla style.
I'm not saying that your idea is right or wrong, just that it's about "taste".
It could be proposed to add the option to customize RGB of light sources, as is in other shaders.

**Comment by Kinda-Stormy** [comment]
That could be really cool.

**Comment by Kinda-Stormy** [comment]
Anyways, I will close this for now
