### ISSUE TITLE
Add physics mod support 

### ISSUE THREAD

**Issue by The-Bombastic** [sixthsurge/photon#82]
### Description

It would be very cool to play with a physics mod and this shader.

**Comment by Patomosm** [comment]
Mod support is not shader dependent. At most, a few glitches may appear.
Let us know if you have any issues with Physic Mods.

**Comment by xlifi** [comment]
> Mod support is not shader dependent. At most, a few glitches may appear. Let us know if you have any issues with Physic Mods.

for physics mod it is
https://github.com/haubna/PhysicsMod?tab=readme-ov-file#shaders

**Comment by sixthsurge** [comment]
duplicate of #56
