### ISSUE TITLE
No visible lightning strikes

### ISSUE THREAD

**Issue by Pojbesy5678** [sixthsurge/photon#89]
### What happened?

No visible lightning strikes

### Minecraft Version

1.20.1

### Which shader mod are you using?

Iris

### Shader mod version

Photon shader 

### Shader settings

```conf
Photon shader in general
```

**Comment by Patomosm** [comment]
Same as #13

**Comment by Pojbesy5678** [comment]
Hi, yeah I realised that a few days ago, I can't figure out how to delete
the issue though, sorry about that, I've closed it for now but I'll see if
I can delete it permanently
