### ISSUE TITLE
When going to the nether the entire view port is bordeaux red

### ISSUE THREAD

**Issue by Z3bzonic** [sixthsurge/photon#9]
After enjoying an amazing job well done in the overworld, I decided to go to the nether.
There I only see one color and my crosshair minimap and overlays.
When disabling photon my visuals are back.
This is with vanilla textures (was using stratum x128).
![photonbug](https://user-images.githubusercontent.com/107925003/229739035-344eb297-c44b-4709-b22e-0c3caf609f9f.jpg)

The graka load is then next to 0 then.

**Comment by sixthsurge** [comment]
hello, photon does not have dimension support just yet since it's still a WIP, but it will do very soon ;)

**Comment by Z3bzonic** [comment]
Oh that explains! I will try to fix my world and keep an eye out for updates. Thank you
