### ISSUE TITLE
Gbuffers_Line error, pixelated screen and sun

### ISSUE THREAD

**Issue by JayDinius** [sixthsurge/photon#96]
### What happened?

Playing on 1.20.1, Forge(47.2.0) and Optifine(HD_U_I6_pre6) RTX 3060, Drivers are up to date. Getting Gbuffers_line error, don't know whats causing it, tried to change every setting but nothing worked. 
While doing that i've found out if bloom is turned on, but motion blur is not, i'm getting a pixelated sun and screen. But it might be the Gbuffer error.

*Edit, i've installed 1.20.2 Forge and Optifine, 1.20.4 and optifine aswell. Downgraded my driver from 551.23 to 546.65.
Nothing worked so far. I'll try more troubleshooting. 

![Screenshot 2024-02-09 013758](https://github.com/sixthsurge/photon/assets/159499703/03d901d6-1336-43c7-a02d-fc67edec527c) the screen shot 
![Screenshot 2024-02-09 021243](https://github.com/sixthsurge/photon/assets/159499703/db05b69b-39e8-4c42-b23c-2805840d0aec)

[photon-main.zip](https://github.com/sixthsurge/photon/files/14216157/photon-main.zip)
The Photon Shader which i'm using which causes my bug.

### Minecraft Version

1.20.1

### Which shader mod are you using?

Optifine

### Shader mod version

It just says Photon-main

### Shader settings

```conf


```

**Comment by OKHI233** [comment]
I can't reproduce this even though I'm also receiving the "gbuffers_line" error (see #84), anyway, in my testing, this error message is not present in 1.16.5, so OptiFine probably messed it up somewhere between it and 1.19.4. 

Also, I suggest you to checkout Sodium+Iris, or Embeddium+Oculus if you perfer Forge/NeoForge, as I don't have this problem there and they generally perform better. If you miss some of the feature of OptiFine (such as zooming, connected glass etc), you can checkout this list: https://optifine.alternatives.lambdaurora.dev.

**Comment by JayDinius** [comment]
Yes, it's optifine. Installed Fabric(1.20.2) with sodium and iris and I'm not getting any Gbuffer_Line errors. I guess the creater messed something up in the last couple of version. Might aswell switch completly to fabric on my next server. Had some rendering issues too with some mods with optifine installed. 

But, I've found a other version of this shader on the shaderLABS discord, which works almost fine for me. 

Thanks for the tip with fabric!

I'll call it with that closed and solved. Just have to wait till optifine fixes it.
